% This code translates mixed_models.R to matlab (p-values compared for
% inital dataset).
% It relies on files generated by
% pattern_similarity_no_outlier_trials_load_data_btwn_runs.R (with with
% MIXED_MODELS_FLAG = 1)
initialize_ABCDCon_MGS

summary_file1 = fullfile(analMRIDir, '\multivariate_sanityCheck','group_temporal_trial_patterns.csv');
summary_file2 = fullfile(analMRIDir, '\multivariate_sanityCheck','group_spatial_trial_patterns.csv');

group_temporal_trial_patterns = readtable(summary_file1,'Delimiter',',');
group_spatial_trial_patterns = readtable(summary_file2,'Delimiter',',');
alldata_table =  [ group_temporal_trial_patterns; group_spatial_trial_patterns ];

% fisher zscore data
A = alldata_table.r;
alldata_table.z = 1/2*(log((1+A)./(1-A)));

% Focus on hip body
A = find(ismember(alldata_table.roi, 'ERC' ));
alldata_table(A,:) = [];
A = find(ismember(alldata_table.roi, 'subiculum' ));
alldata_table(A,:) = [];

% We remove the sameHouse_eitherRoom condition which is included in other
% conditions
A = find(ismember(alldata_table.condition, 'sameHouse_eitherRoom' ));
alldata_table_reduced = alldata_table;
alldata_table_reduced(A,:) = [];
unique(alldata_table_reduced.condition)

% 23 subjects in Halle's database
Ns = length(unique(alldata_table_reduced.subj));
disp([num2str(Ns),' subjects'])
unique(alldata_table_reduced.roi)

formula = 'z~condition*roi + condition*hemi + roi*hemi + (1|subj)';
lme1 = fitlme(alldata_table_reduced,formula);
formula = 'z~condition*roi*hemi + (1|subj)';
lme2 = fitlme(alldata_table_reduced,formula);
results = compare(lme1,lme2);

% A significnat 3-way interaction for condition/roi/hem - P = 0.017

% Left hemisphere only
A = find(ismember(alldata_table_reduced.hemi, 'right' ));  % remove right-hem entries
alldata_table_reduced_left = alldata_table_reduced;
alldata_table_reduced_left(A,:) = [];
unique(alldata_table_reduced_left.hemi)

formula = 'z~condition+roi + (1|subj)';
lme1 = fitlme(alldata_table_reduced_left,formula);
formula = 'z~condition*roi + (1|subj)';
lme2 = fitlme(alldata_table_reduced_left,formula);
results = compare(lme1,lme2);
% no significnat 2-way interaction in left hem for condition/roi - P = 0.07


% left hemisphere 'ca1' - checking context effect
% comparing same video/house to diffVideo/sameHouse
% (With halle's dataset - P = 0.01)
row_num = find(ismember(alldata_table_reduced_left.roi,'CA1_body') & ~ismember(alldata_table_reduced_left.condition,'differentHouse_eitherRoom'));
alldata_table_left_ca1_body = alldata_table_reduced_left(row_num,:);
formula = 'z ~ 1+(1|subj) ';
lme1 = fitlme(alldata_table_left_ca1_body,formula);
formula = 'z~condition + (1|subj)';
lme2 = fitlme(alldata_table_left_ca1_body,formula);
results = compare(lme1,lme2);

% left hemisphere 'ca23dg' - checking context effect
% comparing same video/house to diffVideo/sameHouse
% (With halle's dataset - P = 0.001)
row_num = find(ismember(alldata_table_reduced_left.roi,'CA2_3_DG_body') & ~ismember(alldata_table_reduced_left.condition,'differentHouse_eitherRoom'));
alldata_table_left_ca23dg_body = alldata_table_reduced_left(row_num,:);
formula = 'z ~ 1+(1|subj) ';
lme1 = fitlme(alldata_table_left_ca23dg_body,formula);
formula = 'z~condition + (1|subj)';
lme2 = fitlme(alldata_table_left_ca23dg_body,formula);
results = compare(lme1,lme2);

