#' Collecting mixed-models stats - looking at the effect of room-placement in virtual environment
#' 
#' 
#' 

#+ initialize, warning = FALSE, message = FALSE
devtools::load_all()

# add dplyr with library()
# NB: this is non-standard
# correct way would be to make this script into a function,
# store in the R/ directory,
# and use @importFrom dplyr "%>%",
# but this is incompatible with getting in-line results with code in knitr output
library(dplyr)


#' This CSV file was generated by prepare_tables_mixed_models_space_knowledge.m
spatial_trials = read.csv("E:\\spatcon_hdz\\data_p\\analyzed_mri_mixed_items\\multivariate_sanityCheck\\allData_spaceCond_Rhit_QA_runs_rmv.csv")

#' ## List included subjects
unique(spatial_trials$subj)

#' # Mixed models setup, in line with methods used in Dimsdale-Zucker et al, 2018

#' fixed effects: condition, roi, condition*roi
#' random effects: subj
#' ## Z-score single trials
spatial_trials_z <-
  spatial_trials %>%
  as.data.frame() %>%
  dplyr::mutate(z_r = halle::fisher_r_to_z(r))

#' Focus on 
#'     tested ROIs 
#'     items seen in the same house 
#'     items that were identified correctly
#'     remove temporal context (only diff videos)
all_trials_body <-
  spatial_trials_z %>%
  dplyr::filter(roi %in% c("CA1_body", "CA2_3_DG_body")) %>%
  dplyr::filter(condition1 %in% c("knownRoom")) %>%
  dplyr::filter(condition %in% c("differentVideo_sameHouse")) %>%
  droplevels(.)

unique(all_trials_body$condition1)
unique(all_trials_body$entryRoom)
unique(all_trials_body$roi)
unique(all_trials_body$condition)

lmm.null.DV <- lme4::lmer(z_r ~ entryRoom + roi + (1|subj), data = all_trials_body, REML = FALSE)
summary(lmm.null.DV)

lmm.no_random_slopes.DV.roi_loc <- lme4::lmer(z_r ~ entryRoom*roi + (1|subj), data = all_trials_body, REML = FALSE)
summary(lmm.no_random_slopes.DV.roi_loc)

#' ### model comparison (interaction between roi and room-location)
anova(lmm.null.DV, lmm.no_random_slopes.DV.roi_loc)


#' ## CA1 only 
all_trials_body_DVSH_CA1 <-
  all_trials_body %>%
  dplyr::filter(roi == "CA1_body") %>%
  droplevels(.)

unique(all_trials_body_DVSH_CA1$condition)

lmm.null.CA1.spatial <- lme4::lmer(z_r ~ (1|subj), data = all_trials_body_DVSH_CA1, REML = FALSE)
summary(lmm.null.CA1.spatial)

lmm.DVSH_DVDH.no_random_slopes.CA1 <- lme4::lmer(z_r ~ entryRoom + (1|subj), data = all_trials_body_DVSH_CA1, REML = FALSE)
summary(lmm.DVSH_DVDH.no_random_slopes.CA1)

#' ### model comparison (CA1: Spatial Context Similarity)
anova(lmm.null.CA1.spatial, lmm.DVSH_DVDH.no_random_slopes.CA1)


#' ## CA23 only 
all_trials_body_DVSH_CA23 <-
  all_trials_body %>%
  dplyr::filter(roi == "CA2_3_DG_body") %>%
  droplevels(.)

unique(all_trials_body_DVSH_CA23$entryRoom)

lmm.null.CA23DG.spatial <- lme4::lmer(z_r ~ (1|subj), data = all_trials_body_DVSH_CA23, REML = FALSE)
summary(lmm.null.CA23DG.spatial)

lmm.DVSH_DVDH.no_random_slopes.CA23DG <- lme4::lmer(z_r ~ entryRoom + (1|subj), data = all_trials_body_DVSH_CA23, REML = FALSE)
summary(lmm.DVSH_DVDH.no_random_slopes.CA23DG)

#' ### model comparison ( CA23DG: Spatial Context Similarity)
anova(lmm.null.CA23DG.spatial, lmm.DVSH_DVDH.no_random_slopes.CA23DG)

#' ----------------------------------------------------------------------------------
#' repeat previous analysis for different houses 
#' Focus on 
#'     tested ROIs 
#'     items seen in different houses  
#'     items that were identified correctly
#'     remove temporal context (only diff videos)
all_trials_body <-
  spatial_trials_z %>%
  dplyr::filter(roi %in% c("CA1_body", "CA2_3_DG_body")) %>%
  dplyr::filter(condition1 %in% c("knownRoom")) %>%
  dplyr::filter(condition %in% c("differentHouse_eitherRoom")) %>%
  droplevels(.)

unique(all_trials_body$condition1)
unique(all_trials_body$entryRoom)
unique(all_trials_body$roi)
unique(all_trials_body$condition)

lmm.null.DV <- lme4::lmer(z_r ~ entryRoom + roi + (1|subj), data = all_trials_body, REML = FALSE)
summary(lmm.null.DV)

lmm.no_random_slopes.DV.roi_loc <- lme4::lmer(z_r ~ entryRoom*roi + (1|subj), data = all_trials_body, REML = FALSE)
summary(lmm.no_random_slopes.DV.roi_loc)

#' ### model comparison (interaction between roi and room-location)
anova(lmm.null.DV, lmm.no_random_slopes.DV.roi_loc)


#' ## CA1
all_trials_body_DVSH_CA1 <-
  all_trials_body %>%
  dplyr::filter(roi == "CA1_body") %>%
  droplevels(.)

unique(all_trials_body_DVSH_CA1$condition)

lmm.null.CA1.spatial <- lme4::lmer(z_r ~ (1|subj), data = all_trials_body_DVSH_CA1, REML = FALSE)
summary(lmm.null.CA1.spatial)

lmm.DVSH_DVDH.no_random_slopes.CA1 <- lme4::lmer(z_r ~ entryRoom + (1|subj), data = all_trials_body_DVSH_CA1, REML = FALSE)
summary(lmm.DVSH_DVDH.no_random_slopes.CA1)

#' ### model comparison (CA1: Spatial Context Similarity)
anova(lmm.null.CA1.spatial, lmm.DVSH_DVDH.no_random_slopes.CA1)


#' ## CA23
all_trials_body_DVSH_CA23 <-
  all_trials_body %>%
  dplyr::filter(roi == "CA2_3_DG_body") %>%
  droplevels(.)

unique(all_trials_body_DVSH_CA23$entryRoom)

lmm.null.CA23DG.spatial <- lme4::lmer(z_r ~ (1|subj), data = all_trials_body_DVSH_CA23, REML = FALSE)
summary(lmm.null.CA23DG.spatial)

lmm.DVSH_DVDH.no_random_slopes.CA23DG <- lme4::lmer(z_r ~ entryRoom + (1|subj), data = all_trials_body_DVSH_CA23, REML = FALSE)
summary(lmm.DVSH_DVDH.no_random_slopes.CA23DG)

#' ### model comparison (CA23DG: Spatial Context Similarity)
anova(lmm.null.CA23DG.spatial, lmm.DVSH_DVDH.no_random_slopes.CA23DG)


#' Testing whether house identity is a factor for entry-room items
#' 


all_trials_body_SR <-
  spatial_trials_z %>%
  dplyr::filter(roi %in% c("CA1_body", "CA2_3_DG_body")) %>%
  dplyr::filter(condition1 %in% c("knownRoom")) %>%
  dplyr::filter(condition %in% c("differentHouse_eitherRoom","differentVideo_sameHouse")) %>%
  dplyr::filter(entryRoom %in% c("entryRoom")) %>%
  droplevels(.)


#' CA1
all_trials_body_SR_CA1 <-
  all_trials_body_SR %>%
  dplyr::filter(roi == "CA1_body") %>%
  droplevels(.)

lmm.null.CA1.spatial <- lme4::lmer(z_r ~ (1|subj), data = all_trials_body_SR_CA1, REML = FALSE)
summary(lmm.null.CA1.spatial)

lmm.DVSH_DVDH.no_random_slopes.CA1 <- lme4::lmer(z_r ~ condition + (1|subj), data = all_trials_body_SR_CA1, REML = FALSE)
summary(lmm.DVSH_DVDH.no_random_slopes.CA1)

#' ### model comparison ( CA1: Spatial Context Similarity)
anova(lmm.null.CA1.spatial, lmm.DVSH_DVDH.no_random_slopes.CA1)


#' CA23DG
all_trials_body_SR_CA23 <-
  all_trials_body_SR %>%
  dplyr::filter(roi == "CA2_3_DG_body") %>%
  droplevels(.)

lmm.null.CA23DG.spatial <- lme4::lmer(z_r ~ (1|subj), data = all_trials_body_SR_CA23, REML = FALSE)
summary(lmm.null.CA23DG.spatial)

lmm.DVSH_DVDH.no_random_slopes.CA23DG <- lme4::lmer(z_r ~ condition + (1|subj), data = all_trials_body_SR_CA23, REML = FALSE)
summary(lmm.DVSH_DVDH.no_random_slopes.CA23DG)

#' ### model comparison ( CA23DG: Spatial Context Similarity)
anova(lmm.null.CA23DG.spatial, lmm.DVSH_DVDH.no_random_slopes.CA23DG)




